Repository scrapd/scrapd, pull requests merged in 2019-03, with the labels that each got.

#57 Make sure date string format is consistent
  CHANGELOG.md
  scrapd/core/apd.py
  scrapd/core/date_utils.py
  tests/core/test_apd.py
  tests/core/test_date_utils.py
Labels: bug

#60 Parse notes from detail page
  scrapd/core/apd.py
  tests/core/test_apd.py
  tests/mock_data.py
  tests/step_defs/test_retrieve.py
Labels: enhancement

#66 Remove duplicate entries
  CHANGELOG.md
  scrapd/core/apd.py
  setup.cfg
  tests/features/retrieve.feature
  tests/step_defs/test_retrieve.py
  tests/test_common.py
Labels: enhancement

#67 Update the documentation
  .github/CONTRIBUTING.rst
  CHANGELOG.md
  README.rst
  contributors.md
Labels: Documentation
